import { Request, Response } from "express";
import { generateService } from "../services/aiService";
import { AppError } from "../utils/appError";





export const generateQuestion = async (req:Request, res:Response)=>{
    try{
        const data = await generateService(req.body);
        console.log(data);
        return res.status(201).json({
            success:true,
            message:"Questions updated successfully",
            data:data,
        })
    }
    catch(error:unknown){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code: error.code, 
                details: error.details,   
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}