import { Request, Response } from "express";
import { generateService } from "../services/aiService";
import { AppError } from "../utils/appError";
import { generateFeedbackService, getFeedbackService } from "../services/feedbackService";





export const generateFeedback = async (req:Request, res:Response)=>{
    try{
        console.log("data from the body-----------");
        console.log(req.body);
        
        const data = await generateFeedbackService(req.body);
        console.log(data);
        return res.status(201).json({
            success:true,
            message:"feedback generated successfully",
            data:data,
        })
    }
    catch(error:unknown){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code: error.code, 
                details: error.details,   
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}

export const getFeedback = async(req:Request, res:Response)=>{
    try{
        const {interviewId, userId} = req.params;
        console.log(interviewId);
        console.log(userId);
        const data = await getFeedbackService(interviewId!, userId!);
        return res.status(200).json({
            success:true,
            message:"feedback fetched successfully",
            data:data,
        })
    }
    catch(error:unknown){
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code: error.code, 
                details: error.details,   
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}