import { Request, Response } from "express";
import { generateService } from "../services/aiService";
import { AppError } from "../utils/appError";
import { getAllInterviewsService, getInterviewByIdService } from "../services/interviewService";





export const getAllInterviews = async (req:Request, res:Response)=>{
    try{
        console.log("data from the body-----------");
        // console.log(req.body);
        const {userId} = req.query as { userId?: string };
        
        
        if (!userId) {
            return res.status(400).json({ error: "Missing userId" });   
        }

        const data = await getAllInterviewsService(userId);
        console.log(data);
        return res.status(201).json({
            success:true,
            message:"Fetched all the interviews",
            data:data,
        })
    }
    catch(error:unknown){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code: error.code, 
                details: error.details,   
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}

export const getInterviewById = async (req:Request<{ id: string }>, res:Response)=>{
    try{
         const { id } = req.params;
        const data = await getInterviewByIdService(id);

        return res.status(201).json({
            success:true,
            message:"Fetched particular interviews",
            data:data,
        })
    }
    catch(error:unknown){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code: error.code, 
                details: error.details,   
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
    
}