import { Request, Response } from "express";
import { signInUserService, signUpUserService } from "../services/userServices";
import { AppError } from "../utils/appError";

export const getuserProfile = async (req:Request,res:Response)=>{
    res.json({
        message: "this is dummy implementation of the userProfiel",
    })
};



export const signUp = async (req:Request, res:Response)=>{
    try{
        const user = await signUpUserService(req.body);
        return res.status(201).json({
            success:true,
            message:"User created Successfully",
            data:user,
        })
    }
    catch(error:unknown){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code: error.code, 
                details: error.details,   
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}

export const signIn = async(req:Request,res:Response)=>{
    try{
        const response = await signInUserService(req.body);
        return res.status(200).json({
            sucess:true,
            message:"user signedIn successfully",
            data: response,
        });

    }catch(error : unknown){
        if(error instanceof AppError){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
                code:error.code,
                details:error.details,
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",
            error:error,

        })
    }
}